### ISSUE TITLE
Action Upgrade to Node 20 

### ISSUE THREAD

**Issue by jdesulme** [Rebilly/lexi#313]
We're running this action in our workflows, and it constantly outputs warning messages that the node version is out of date. It's likely updating the version behind the scenes, but ideally, this action can be updated and rebuilt using a more recent version https://github.com/Rebilly/lexi/blob/main/action.yml#L14-L16. 

Error Messages: 
* Report readability: The following actions uses node12 which is deprecated and will be forced to run on node16: Rebilly/lexi@v2. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/
* Report readability: The following actions use a deprecated Node.js version and will be forced to run on node20: Rebilly/lexi@v2. For more info: https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/

**Comment by jdesulme** [comment]
https://github.blog/changelog/2024-09-25-end-of-life-for-actions-node16/

**Comment by Weetbix** [comment]
Thanks for raising this @jdesulme !

This is fixed in the latest release, `v2.3.0`.

Sorry for the delay!
