### ISSUE TITLE
Bug: Release Process 

### ISSUE THREAD

**Issue by jdesulme** [Rebilly/lexi#314]
It looks like your most recent version of the action doesn't reference your changes. The dist/ directory is different from the code that's being added to the repo. 

It would be best for you to check that the contents match. Something like https://github.com/actions/javascript-action/blob/main/.github/workflows/check-dist.yml.

**Comment by Weetbix** [comment]
Hi @jdesulme thanks for the reports!

We do not release every commit in main, only when there is a feature change or a security related dependency update. So it is not expected that `main` dist matches the latest release. You can find the sha for the latest release in the release notes: https://github.com/Rebilly/lexi/releases/tag/v2.2.0 

Pull requests are already running a [required action to make sure the build is committed correctly](https://github.com/Rebilly/lexi/blob/main/.github/workflows/pr-checks.yml#L47), so if we chose to release a commit it would have a matching `dist` folder.
